name: Build and Deploy WASM App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build WASM Distribution
      run: ./gradlew wasmJsBrowserDistribution

    - name: Copy files to docs folder
      run: |
        rm -rf docs/*
        cp -r build/dist/wasmJs/productionExecutable/* docs/

    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add docs/
        git commit -m "Deploy updated WASM build to GitHub Pages"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Использование встроенного токена для аутентификации
